### PR TITLE
Return errorCode for all failed to load ads

### PR DESCRIPTION
**Pull request by grevius5**
I think it will be useful to have error code returned not only in rewarded video fail but also in banner and interstitial.

### CODE REVIEW

**Comment by Shin-NiL** [comment]
That would be nice. The only drawback here is that it will break the backwards compatibility as it will change these methods signature.

**Comment by grevius5** [comment]
That's true, I understand.
I think some other changes can be made, not all functions name are consistent, but of course, this breaks backward compatibility as well. I'll continue with these changes in my fork if you want to release a "major release" that can hold those changes feel free to contact me :)

**Comment by Shin-NiL** [comment]
>  not all functions name are consistent
Yeah, this is a real issue on this code base. I've some old projects using this module and I think there's many devs in the same situation ;(
Thank you very much, a major release would be a good idea.

**Comment by Shin-NiL** [comment]
The naming makes more sense now, nice!

**Comment by grevius5** [comment]
There is the iPhone section that isn't updated, I don't know how iPhone project work, I have to check it and update also the readme file

**Comment by Shin-NiL** [comment]
Any help with the iPhone documentation will be welcome.

**Comment by gustavottc** [comment]
Closing the pull request because the changes are very different now, please create a fork with the recent changes and make the pull request again @grevius5

**Pull request closed without merging**
